// Editorial curation table: free-exercise-db source id -> FitDuo catalog entry.
// Everything here (pattern, tier, rep ranges, tempo, cues) is our own authoring;
// only name/muscles/media come from the source dataset (Unlicense/public domain).

export interface Curated {
  slug: string
  sourceId: string
  displayName: string
  role: 'warmup' | 'main' | 'cooldown'
  pattern:
    | 'push_h'
    | 'push_v'
    | 'pull_h'
    | 'pull_v'
    | 'squat'
    | 'hinge'
    | 'lunge'
    | 'core'
    | 'carry'
    | 'mobility'
  tier: 1 | 2 | 3
  unilateral: boolean
  repRange: [number, number]
  secondsPerRep: number
  setupSeconds: number
  cues: string[]
}

const W = (
  slug: string,
  sourceId: string,
  displayName: string,
  cues: string[],
): Curated => ({
  slug,
  sourceId,
  displayName,
  role: 'warmup',
  pattern: 'mobility',
  tier: 1,
  unilateral: false,
  repRange: [1, 1], // warmups are timed, reps unused
  secondsPerRep: 1,
  setupSeconds: 5,
  cues,
})

const C = (
  slug: string,
  sourceId: string,
  displayName: string,
  cues: string[],
): Curated => ({
  slug,
  sourceId,
  displayName,
  role: 'cooldown',
  pattern: 'mobility',
  tier: 1,
  unilateral: false,
  repRange: [1, 1], // stretches are timed, reps unused
  secondsPerRep: 1,
  setupSeconds: 5,
  cues,
})

export const SELECTION: Curated[] = [
  // ─── Warm-up (timed, dynamic) ──────────────────────────────────────────────
  W('arm-circles', 'Arm_Circles', 'Arm Circles', [
    'Arms straight out to the sides',
    'Small circles growing to large',
    'Reverse direction halfway',
  ]),
  W('shoulder-circles', 'Shoulder_Circles', 'Shoulder Rolls', [
    'Roll shoulders up, back, and down',
    'Keep arms relaxed',
    'Big, slow circles',
  ]),
  W('dynamic-chest-stretch', 'Dynamic_Chest_Stretch', 'Dynamic Chest Opener', [
    'Swing arms wide, then cross over',
    'Stay tall, ribs down',
    'Smooth rhythm, no bouncing',
  ]),
  W('dynamic-back-stretch', 'Dynamic_Back_Stretch', 'Dynamic Back Reach', [
    'Reach forward and round the upper back',
    'Then open arms and squeeze shoulder blades',
    'Move with your breath',
  ]),
  W('hip-circles', 'Standing_Hip_Circles', 'Hip Circles', [
    'Hands on hips, feet shoulder-width',
    'Draw big circles with your hips',
    'Both directions',
  ]),
  W('ankle-circles', 'Ankle_Circles', 'Ankle Circles', [
    'Balance on one leg or hold support',
    'Circle the ankle both ways',
    'Switch feet halfway',
  ]),
  W('leg-swings', 'Front_Leg_Raises', 'Leg Swings', [
    'Hold a wall for balance',
    'Swing the leg front to back',
    'Controlled, growing range',
  ]),
  W('inchworm', 'Inchworm', 'Inchworm Walkout', [
    'Fold, walk hands out to plank',
    'Keep legs as straight as comfortable',
    'Walk hands back and stand tall',
  ]),
  W('groiners', 'Groiners', 'Hip Opener Lunges', [
    'From plank, step foot outside hand',
    'Sink the hips, chest up',
    'Alternate sides',
  ]),
  W('worlds-greatest-stretch', 'Worlds_Greatest_Stretch', "World's Greatest Stretch", [
    'Deep lunge, opposite hand down',
    'Rotate chest to the sky, reach up',
    'Alternate sides slowly',
  ]),
  W('butt-kicks', 'Double_Leg_Butt_Kick', 'Butt Kicks', [
    'Light jog in place',
    'Kick heels toward glutes',
    'Stay springy on the balls of your feet',
  ]),
  W('star-jumps', 'Star_Jump', 'Star Jumps', [
    'Jump arms and legs wide',
    'Land soft with bent knees',
    'Steady pace, keep breathing',
  ]),
  W('cat-cow', 'Cat_Stretch', 'Cat-Cow', [
    'On all fours, round the spine up',
    'Then arch and lift the chest',
    'Move slowly with your breath',
  ]),
  W('sit-squats', 'Sit_Squats', 'Air Squat Pulses', [
    'Sit back like reaching for a chair',
    'Light and quick, half depth',
    'Warm up the knees and hips',
  ]),

  // ─── Main: horizontal push (chest, triceps) ───────────────────────────────
  {
    slug: 'push-up',
    sourceId: 'Pushups',
    displayName: 'Push-Up',
    role: 'main',
    pattern: 'push_h',
    tier: 1,
    unilateral: false,
    repRange: [6, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Body in one straight line', 'Elbows ~45° from body', 'Chest to the floor, full lockout'],
  },
  {
    slug: 'push-up-feet-elevated',
    sourceId: 'Push-Ups_With_Feet_Elevated',
    displayName: 'Feet-Elevated Push-Up',
    role: 'main',
    pattern: 'push_h',
    tier: 3,
    unilateral: false,
    repRange: [6, 12],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Feet on a sturdy chair or step', 'Brace hard — no sagging hips', 'Lower under control'],
  },
  {
    slug: 'push-up-to-side-plank',
    sourceId: 'Push_Up_to_Side_Plank',
    displayName: 'Push-Up to Side Plank',
    role: 'main',
    pattern: 'push_h',
    tier: 2,
    unilateral: false,
    repRange: [6, 12],
    secondsPerRep: 4,
    setupSeconds: 10,
    cues: ['Push up, then rotate to one arm', 'Stack shoulders, reach for the ceiling', 'Alternate sides'],
  },
  {
    slug: 'db-chest-press',
    sourceId: 'Dumbbell_Bench_Press',
    displayName: 'Dumbbell Chest Press',
    role: 'main',
    pattern: 'push_h',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: [
      'Lie on a mat or bench, feet planted',
      'Press dumbbells over mid-chest',
      'Lower until upper arms touch the floor',
    ],
  },
  {
    slug: 'db-chest-fly',
    sourceId: 'Dumbbell_Flyes',
    displayName: 'Dumbbell Chest Fly',
    role: 'main',
    pattern: 'push_h',
    tier: 2,
    unilateral: false,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Slight bend in elbows, keep it', 'Open arms wide like a hug', 'Squeeze chest to bring them back'],
  },
  {
    slug: 'db-overhead-triceps-extension',
    sourceId: 'Standing_Dumbbell_Triceps_Extension',
    displayName: 'Overhead Triceps Extension',
    role: 'main',
    pattern: 'push_h',
    tier: 1,
    unilateral: false,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['One dumbbell, both hands overhead', 'Elbows stay close to your ears', 'Lower behind head, press up'],
  },
  {
    slug: 'db-triceps-kickback',
    sourceId: 'Tricep_Dumbbell_Kickback',
    displayName: 'Triceps Kickback',
    role: 'main',
    pattern: 'push_h',
    tier: 1,
    unilateral: false,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Hinge forward, flat back', 'Pin upper arms to your sides', 'Straighten fully, squeeze, return slow'],
  },
  {
    slug: 'db-skullcrusher',
    sourceId: 'Lying_Dumbbell_Tricep_Extension',
    displayName: 'Lying Triceps Extension',
    role: 'main',
    pattern: 'push_h',
    tier: 2,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Lie down, dumbbells over shoulders', 'Bend only at the elbows', 'Lower beside your head, press back up'],
  },
  {
    slug: 'chair-dips',
    sourceId: 'Bench_Dips',
    displayName: 'Chair Dips',
    role: 'main',
    pattern: 'push_h',
    tier: 2,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Hands on a sturdy chair edge', 'Lower until elbows hit ~90°', 'Keep shoulders away from ears'],
  },

  // ─── Main: vertical push (shoulders) ──────────────────────────────────────
  {
    slug: 'db-shoulder-press',
    sourceId: 'Standing_Dumbbell_Press',
    displayName: 'Standing Shoulder Press',
    role: 'main',
    pattern: 'push_v',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Dumbbells at shoulder height', 'Press straight up, biceps by ears', 'Ribs down — don’t arch the back'],
  },
  {
    slug: 'db-arnold-press',
    sourceId: 'Arnold_Dumbbell_Press',
    displayName: 'Arnold Press',
    role: 'main',
    pattern: 'push_v',
    tier: 2,
    unilateral: false,
    repRange: [8, 12],
    secondsPerRep: 4,
    setupSeconds: 10,
    cues: ['Start palms facing you', 'Rotate out as you press up', 'Reverse the spiral on the way down'],
  },
  {
    slug: 'db-lateral-raise',
    sourceId: 'Side_Lateral_Raise',
    displayName: 'Lateral Raise',
    role: 'main',
    pattern: 'push_v',
    tier: 1,
    unilateral: false,
    repRange: [10, 18],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Slight bend in the elbows', 'Raise to shoulder height, no higher', 'Lead with elbows, pour the jug'],
  },
  {
    slug: 'db-front-raise',
    sourceId: 'Front_Dumbbell_Raise',
    displayName: 'Front Raise',
    role: 'main',
    pattern: 'push_v',
    tier: 1,
    unilateral: false,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Raise to eye level, arms straight', 'No swinging — strict and slow', 'Alternate or together'],
  },

  // ─── Main: horizontal pull (back, rear delts, biceps) ─────────────────────
  {
    slug: 'db-bent-over-row',
    sourceId: 'Bent_Over_Two-Dumbbell_Row',
    displayName: 'Bent-Over Row',
    role: 'main',
    pattern: 'pull_h',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Hinge to ~45°, flat back', 'Row to your hips, not your chest', 'Squeeze shoulder blades together'],
  },
  {
    slug: 'db-one-arm-row',
    sourceId: 'One-Arm_Dumbbell_Row',
    displayName: 'One-Arm Row',
    role: 'main',
    pattern: 'pull_h',
    tier: 1,
    unilateral: true,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Support on a chair or knee', 'Pull elbow back past your ribs', 'No torso twist — stay square'],
  },
  {
    slug: 'db-reverse-fly',
    sourceId: 'Reverse_Flyes',
    displayName: 'Reverse Fly',
    role: 'main',
    pattern: 'pull_h',
    tier: 1,
    unilateral: false,
    repRange: [10, 18],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Hinge forward, soft elbows', 'Open arms wide like wings', 'Squeeze between the shoulder blades'],
  },
  {
    slug: 'db-bicep-curl',
    sourceId: 'Dumbbell_Bicep_Curl',
    displayName: 'Biceps Curl',
    role: 'main',
    pattern: 'pull_h',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 5,
    cues: ['Elbows pinned to your sides', 'Curl up, squeeze at the top', 'Lower slow — no swinging'],
  },
  {
    slug: 'db-hammer-curl',
    sourceId: 'Hammer_Curls',
    displayName: 'Hammer Curl',
    role: 'main',
    pattern: 'pull_h',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 5,
    cues: ['Palms face each other', 'Curl without moving the elbows', 'Control the way down'],
  },
  {
    slug: 'db-concentration-curl',
    sourceId: 'Concentration_Curls',
    displayName: 'Concentration Curl',
    role: 'main',
    pattern: 'pull_h',
    tier: 2,
    unilateral: true,
    repRange: [8, 12],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Seated, elbow braced on inner thigh', 'Curl slow, squeeze hard at top', 'Full stretch at the bottom'],
  },

  // ─── Main: vertical pull-ish (lats, traps) ────────────────────────────────
  {
    slug: 'db-pullover',
    sourceId: 'Bent-Arm_Dumbbell_Pullover',
    displayName: 'Dumbbell Pullover',
    role: 'main',
    pattern: 'pull_v',
    tier: 2,
    unilateral: false,
    repRange: [8, 12],
    secondsPerRep: 4,
    setupSeconds: 15,
    cues: ['Lie down, one dumbbell in both hands', 'Lower it behind your head, arc slowly', 'Pull back over your chest — ribs down'],
  },
  {
    slug: 'db-upright-row',
    sourceId: 'Standing_Dumbbell_Upright_Row',
    displayName: 'Upright Row',
    role: 'main',
    pattern: 'pull_v',
    tier: 2,
    unilateral: false,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 5,
    cues: ['Pull dumbbells up your body line', 'Elbows lead, stop at chest height', 'Keep wrists relaxed'],
  },
  {
    slug: 'db-shrug',
    sourceId: 'Dumbbell_Shrug',
    displayName: 'Dumbbell Shrug',
    role: 'main',
    pattern: 'pull_v',
    tier: 1,
    unilateral: false,
    repRange: [10, 18],
    secondsPerRep: 2,
    setupSeconds: 5,
    cues: ['Shoulders straight up to your ears', 'Pause a beat at the top', 'Long arms — no elbow bend'],
  },

  // ─── Main: squat ──────────────────────────────────────────────────────────
  {
    slug: 'db-squat',
    sourceId: 'Dumbbell_Squat',
    displayName: 'Dumbbell Squat',
    role: 'main',
    pattern: 'squat',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Dumbbells at your sides or shoulders', 'Sit back and down, chest proud', 'Drive through mid-foot to stand'],
  },
  {
    slug: 'bodyweight-squat',
    sourceId: 'Bodyweight_Squat',
    displayName: 'Bodyweight Squat',
    role: 'main',
    pattern: 'squat',
    tier: 1,
    unilateral: false,
    repRange: [10, 20],
    secondsPerRep: 3,
    setupSeconds: 5,
    cues: ['Feet shoulder-width, toes slightly out', 'Hips below parallel if comfortable', 'Knees track over toes'],
  },
  {
    slug: 'db-sumo-squat',
    sourceId: 'Plie_Dumbbell_Squat',
    displayName: 'Sumo Squat',
    role: 'main',
    pattern: 'squat',
    tier: 1,
    unilateral: false,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Wide stance, toes out, one dumbbell', 'Sink straight down between the knees', 'Squeeze glutes on the way up'],
  },
  {
    slug: 'jump-squat',
    sourceId: 'Freehand_Jump_Squat',
    displayName: 'Jump Squat',
    role: 'main',
    pattern: 'squat',
    tier: 2,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 5,
    cues: ['Squat down, explode up', 'Land soft, sink into the next rep', 'Arms drive the jump'],
  },
  {
    slug: 'db-calf-raise',
    sourceId: 'Standing_Dumbbell_Calf_Raise',
    displayName: 'Standing Calf Raise',
    role: 'main',
    pattern: 'squat',
    tier: 1,
    unilateral: false,
    repRange: [12, 20],
    secondsPerRep: 2,
    setupSeconds: 5,
    cues: ['Rise high onto the balls of your feet', 'Pause at the top', 'Lower slowly past level if on a step'],
  },

  // ─── Main: hinge ──────────────────────────────────────────────────────────
  {
    slug: 'db-romanian-deadlift',
    sourceId: 'Stiff-Legged_Dumbbell_Deadlift',
    displayName: 'Romanian Deadlift',
    role: 'main',
    pattern: 'hinge',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Push hips back, soft knees', 'Dumbbells slide down your thighs', 'Feel the hamstrings, then stand tall'],
  },
  {
    slug: 'db-clean',
    sourceId: 'Dumbbell_Clean',
    displayName: 'Dumbbell Clean',
    role: 'main',
    pattern: 'hinge',
    tier: 3,
    unilateral: false,
    repRange: [6, 10],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Hinge, then explode hips forward', 'Pull dumbbells to your shoulders', 'Catch soft with bent knees'],
  },
  {
    slug: 'glute-bridge',
    sourceId: 'Butt_Lift_Bridge',
    displayName: 'Glute Bridge',
    role: 'main',
    pattern: 'hinge',
    tier: 1,
    unilateral: false,
    repRange: [10, 20],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Heels close to your hips', 'Drive hips up, squeeze glutes hard', 'One line from knees to shoulders'],
  },
  {
    slug: 'single-leg-glute-bridge',
    sourceId: 'Single_Leg_Glute_Bridge',
    displayName: 'Single-Leg Glute Bridge',
    role: 'main',
    pattern: 'hinge',
    tier: 2,
    unilateral: true,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['One foot down, other leg extended', 'Hips level — don’t let them tilt', 'Squeeze at the top each rep'],
  },
  {
    slug: 'superman',
    sourceId: 'Superman',
    displayName: 'Superman Hold',
    role: 'main',
    pattern: 'hinge',
    tier: 1,
    unilateral: false,
    repRange: [8, 15],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Lie face down, arms extended', 'Lift arms and legs together', 'Squeeze the whole back line, lower slow'],
  },

  // ─── Main: lunge ──────────────────────────────────────────────────────────
  {
    slug: 'db-lunge',
    sourceId: 'Dumbbell_Lunges',
    displayName: 'Walking Lunge',
    role: 'main',
    pattern: 'lunge',
    tier: 1,
    unilateral: true,
    repRange: [8, 12],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Long step, both knees to 90°', 'Back knee kisses the floor', 'Push through the front heel'],
  },
  {
    slug: 'db-reverse-lunge',
    sourceId: 'Dumbbell_Rear_Lunge',
    displayName: 'Reverse Lunge',
    role: 'main',
    pattern: 'lunge',
    tier: 1,
    unilateral: true,
    repRange: [8, 12],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Step back, drop the back knee', 'Front shin stays vertical', 'Drive up through the front foot'],
  },
  {
    slug: 'db-split-squat',
    sourceId: 'Split_Squat_with_Dumbbells',
    displayName: 'Split Squat',
    role: 'main',
    pattern: 'lunge',
    tier: 2,
    unilateral: true,
    repRange: [8, 12],
    secondsPerRep: 3,
    setupSeconds: 15,
    cues: ['Staggered stance, stay in place', 'Straight down and up like an elevator', 'Finish all reps, then switch legs'],
  },
  {
    slug: 'db-step-up',
    sourceId: 'Dumbbell_Step_Ups',
    displayName: 'Step-Up',
    role: 'main',
    pattern: 'lunge',
    tier: 2,
    unilateral: true,
    repRange: [8, 12],
    secondsPerRep: 4,
    setupSeconds: 15,
    cues: ['Use a sturdy step or low bench', 'Drive through the top heel', 'Lower under control — don’t drop'],
  },
  {
    slug: 'split-jump',
    sourceId: 'Split_Jump',
    displayName: 'Jumping Lunge',
    role: 'main',
    pattern: 'lunge',
    tier: 3,
    unilateral: false,
    repRange: [8, 14],
    secondsPerRep: 2,
    setupSeconds: 5,
    cues: ['Lunge, jump, switch legs mid-air', 'Land soft into the next lunge', 'Keep chest tall throughout'],
  },

  // ─── Main: core ───────────────────────────────────────────────────────────
  {
    slug: 'plank',
    sourceId: 'Plank',
    displayName: 'Plank',
    role: 'main',
    pattern: 'core',
    tier: 1,
    unilateral: false,
    repRange: [1, 1],
    secondsPerRep: 40, // timed hold: reps=1, tempo carries the duration
    setupSeconds: 10,
    cues: ['Forearms down, body in one line', 'Squeeze glutes, brace the belly', 'Breathe — don’t hold your breath'],
  },
  {
    slug: 'side-plank',
    sourceId: 'Side_Bridge',
    displayName: 'Side Plank',
    role: 'main',
    pattern: 'core',
    tier: 2,
    unilateral: true,
    repRange: [1, 1],
    secondsPerRep: 30,
    setupSeconds: 10,
    cues: ['Elbow under shoulder, feet stacked', 'Lift hips into one straight line', 'Hold, then switch sides'],
  },
  {
    slug: 'dead-bug',
    sourceId: 'Dead_Bug',
    displayName: 'Dead Bug',
    role: 'main',
    pattern: 'core',
    tier: 1,
    unilateral: false,
    repRange: [8, 14],
    secondsPerRep: 4,
    setupSeconds: 10,
    cues: ['Low back pressed into the floor', 'Opposite arm and leg reach away', 'Slow and controlled, exhale as you extend'],
  },
  {
    slug: 'russian-twist',
    sourceId: 'Russian_Twist',
    displayName: 'Russian Twist',
    role: 'main',
    pattern: 'core',
    tier: 2,
    unilateral: false,
    repRange: [10, 20],
    secondsPerRep: 2,
    setupSeconds: 10,
    cues: ['Lean back, chest proud', 'Rotate shoulder to shoulder', 'Add a dumbbell to progress'],
  },
  {
    slug: 'reverse-crunch',
    sourceId: 'Reverse_Crunch',
    displayName: 'Reverse Crunch',
    role: 'main',
    pattern: 'core',
    tier: 1,
    unilateral: false,
    repRange: [10, 18],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Knees to chest, lift the hips', 'Roll the spine up, not a swing', 'Lower legs slowly'],
  },
  {
    slug: 'bent-knee-hip-raise',
    sourceId: 'Bent-Knee_Hip_Raise',
    displayName: 'Lying Knee Raise',
    role: 'main',
    pattern: 'core',
    tier: 1,
    unilateral: false,
    repRange: [10, 18],
    secondsPerRep: 3,
    setupSeconds: 10,
    cues: ['Hands by your sides, knees bent', 'Draw knees toward your chest', 'Keep the low back quiet'],
  },
  {
    slug: 'db-side-bend',
    sourceId: 'Dumbbell_Side_Bend',
    displayName: 'Dumbbell Side Bend',
    role: 'main',
    pattern: 'core',
    tier: 1,
    unilateral: true,
    repRange: [10, 15],
    secondsPerRep: 3,
    setupSeconds: 5,
    cues: ['One dumbbell, slide down your side', 'Pull back up with the opposite obliques', 'No leaning forward or back'],
  },
  {
    slug: 'mountain-climber',
    sourceId: 'Spider_Crawl',
    displayName: 'Spider Climbers',
    role: 'main',
    pattern: 'core',
    tier: 2,
    unilateral: false,
    repRange: [10, 20],
    secondsPerRep: 2,
    setupSeconds: 10,
    cues: ['From plank, knee to outside elbow', 'Hips low and level', 'Alternate with rhythm'],
  },

  // ─── Cool-down (timed static stretches) ───────────────────────────────────
  C('childs-pose', 'Childs_Pose', "Child's Pose", [
    'Knees wide, sit back on your heels',
    'Arms long, forehead to the floor',
    'Slow deep breaths',
  ]),
  C('seated-hamstring-stretch', 'Seated_Floor_Hamstring_Stretch', 'Seated Hamstring Stretch', [
    'Legs long, hinge from the hips',
    'Reach toward your toes',
    'Relax the neck, keep breathing',
  ]),
  C('kneeling-hip-flexor-stretch', 'Kneeling_Hip_Flexor', 'Kneeling Hip Flexor Stretch', [
    'Half-kneel, tuck the tailbone',
    'Shift hips gently forward',
    'Reach the same-side arm overhead',
  ]),
  C('side-quad-stretch', 'On_Your_Side_Quad_Stretch', 'Side-Lying Quad Stretch', [
    'Lie on your side, grab the top ankle',
    'Pull the heel toward your glutes',
    'Keep knees together, hips forward',
  ]),
  C('spinal-twist', 'Knee_Across_The_Body', 'Lying Spinal Twist', [
    'On your back, drop one knee across',
    'Both shoulders stay on the floor',
    'Look the opposite way, breathe',
  ]),
  C('figure-four-stretch', 'Ankle_On_The_Knee', 'Figure-4 Glute Stretch', [
    'Ankle over the opposite knee',
    'Pull the lower thigh toward you',
    'Feel it deep in the glute',
  ]),
  C('chest-stretch', 'Chest_And_Front_Of_Shoulder_Stretch', 'Chest & Shoulder Stretch', [
    'Clasp hands behind your back',
    'Lift the knuckles, open the chest',
    'Shoulders down away from ears',
  ]),
  C('overhead-triceps-stretch', 'Triceps_Stretch', 'Overhead Triceps Stretch', [
    'Elbow up, hand down your back',
    'Gently pull the elbow across',
    'Switch arms halfway',
  ]),
  C('cross-shoulder-stretch', 'Shoulder_Stretch', 'Cross-Body Shoulder Stretch', [
    'Arm across the chest',
    'Hug it in with the other arm',
    'Keep the shoulder relaxed',
  ]),
  C('neck-stretch', 'Side_Neck_Stretch', 'Side Neck Stretch', [
    'Ear toward shoulder, gently',
    'Opposite arm reaches down',
    'Switch sides halfway',
  ]),
  C('standing-calf-stretch', 'Standing_Gastrocnemius_Calf_Stretch', 'Calf Stretch', [
    'Back leg straight, heel down',
    'Lean into a wall or chair',
    'Switch legs halfway',
  ]),
  C('knees-to-chest', 'Hug_Knees_To_Chest', 'Knees-to-Chest Hug', [
    'On your back, hug both knees in',
    'Rock gently side to side',
    'Let the low back release',
  ]),
]
